// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnYzpiNUZiqA9cRKO35DBUnzBWqZ6yhWs',
    appId: '1:792946078360:web:ea64094d161edef6ca16ed',
    messagingSenderId: '792946078360',
    projectId: 'real-time-2024',
    authDomain: 'real-time-2024.firebaseapp.com',
    storageBucket: 'real-time-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhffuMdqqywcDoWg6abN8F2NMRavlJYM4',
    appId: '1:792946078360:android:41ca0e1f96b35eddca16ed',
    messagingSenderId: '792946078360',
    projectId: 'real-time-2024',
    storageBucket: 'real-time-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx3bTuqBE2w47lMILba5KA-_F7VDafG_s',
    appId: '1:792946078360:ios:852ad205075d9811ca16ed',
    messagingSenderId: '792946078360',
    projectId: 'real-time-2024',
    storageBucket: 'real-time-2024.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx3bTuqBE2w47lMILba5KA-_F7VDafG_s',
    appId: '1:792946078360:ios:852ad205075d9811ca16ed',
    messagingSenderId: '792946078360',
    projectId: 'real-time-2024',
    storageBucket: 'real-time-2024.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnYzpiNUZiqA9cRKO35DBUnzBWqZ6yhWs',
    appId: '1:792946078360:web:100f012f21a7ba05ca16ed',
    messagingSenderId: '792946078360',
    projectId: 'real-time-2024',
    authDomain: 'real-time-2024.firebaseapp.com',
    storageBucket: 'real-time-2024.appspot.com',
  );
}
